wushu/urls.py
from django.conf.urls import url

from wushu.Views import DashboardViews, AthleteViews, CompetitionViews, CoachViews, ObserverViews, OfficerViews, \
    JudgeViews, FederationViews, UsersViews

app_name = 'wushu'

urlpatterns = [

    # Dashboard
    url(r'anasayfa/admin/$', DashboardViews.return_admin_dashboard, name='admin'),
    url(r'anasayfa/federation/$', DashboardViews.return_federation_dashboard, name='federasyon'),

    # Sporcular
    url(r'sporcu/sporcu-ekle/$', AthleteViews.return_add_athlete, name='sporcu-ekle'),
    url(r'sporcu/sporcular/$', AthleteViews.return_athletes, name='sporcular'),
    url(r'sporcu/sporcuDuzenle/(?P<pk>\d+)$', AthleteViews.updateathletes, name='update-athletes'),
    url(r'sporcu/sporcu-sil/(?P<pk>\d+)$', AthleteViews.delete_athlete, name='delete-athlete'),

    # Competition
    url(r'musabaka/musabakalar/$', CompetitionViews.return_competitions, name='musabakalar'),
    url(r'musabaka/musabaka-ekle/$', CompetitionViews.musabaka_ekle, name='musabaka-ekle'),
    url(r'musabaka/musabaka-duzenle/(?P<pk>\d+)$', CompetitionViews.musabaka_duzenle, name='musabaka-duzenle'),
    url(r'musabaka/musabakalar/musabaka-sil(?P<pk>\d+)$', CompetitionViews.musabaka_sil, name='musabaka-sil'),

    url(r'musabaka/musabaka-sanda-sporcu-sec/(?P<pk>\d+)$', CompetitionViews.musabaka_sanda,
        name='musabaka-sanda-ekle'),
    url(r'musabaka/musabaka-taolu-sporcu-sec/(?P<pk>\d+)/$', CompetitionViews.musabaka_taolu,
        name='musabaka-taolu-ekle'),
    url(r'musabaka/SporcuSecim/Taolu/$', CompetitionViews.return_sporcu_sec_taolu, name='taolu-sporcu-sec-ajax'),
    url(r'musabaka/musabaka-taolu-sporcu-kaydet/$', CompetitionViews.musabaka_taolu_sporcu_ekle,
        name='taolu-sporcu-kaydet'),
    url(r'musabaka/musabaka-duzenle/taolu-kaldir/(?P<pk>\d+)/$', CompetitionViews.musabaka_sporcu_sil_taolu,
        name='musabaka-sporcu-kaldir_taolu'),
    url(r'musabaka/musabaka-duzenle/sanda-kaldir/(?P<pk>\d+)/$', CompetitionViews.musabaka_sporcu_sil,
        name='musabaka-sporcu-kaldir'),
    url(r'musabaka/SporcuSecim/Sanda/$', CompetitionViews.return_sporcu_sec_sanda, name='sanda-sporcu-sec-ajax'),
    url(r'musabaka/musabaka-sanda-sporcu-kaydet/$', CompetitionViews.musabaka_sanda_sporcu_ekle,
        name='sanda-sporcu-kaydet'),
    url(r'musabaka/taolu_year_transmission/$', CompetitionViews.taolu_year_transmission,
        name='taolu_year_transmission'),

    # Coachs
    url(r'coach/add-coach/$', CoachViews.return_add_coach, name='add-coach'),
    url(r'coach/coaches/$', CoachViews.return_coaches, name='coaches'),
    url(r'coach/update-coach/(?P<pk>\d+)$', CoachViews.updatecoaches, name='update-coaches'),
    url(r'coach/delete-coach/(?P<pk>\d+)$', CoachViews.delete_coach, name='delete-coach'),

    # Observers
    url(r'observer/add-observer/$', ObserverViews.return_add_observer, name='add-observer'),
    url(r'observer/observers/$', ObserverViews.return_observers, name='observers'),
    url(r'observer/update-observer/(?P<pk>\d+)$', ObserverViews.updateobservers, name='update-observers'),
    url(r'observer/delete-observer/(?P<pk>\d+)$', ObserverViews.delete_observer, name='delete-observer'),

    # Officers
    url(r'officer/add-officer/$', OfficerViews.return_add_officer, name='add-officer'),
    url(r'officer/officers/$', OfficerViews.return_officers, name='officers'),
    url(r'officer/update-officer/(?P<pk>\d+)$', OfficerViews.updateofficers, name='update-officers'),
    url(r'officer/delete-officer/(?P<pk>\d+)$', OfficerViews.delete_officer, name='delete-officer'),

    # Judge
    url(r'judge/add-judge/$', JudgeViews.return_add_judge, name='add-judge'),
    url(r'judge/judges/$', JudgeViews.return_judges, name='judges'),
    url(r'judge/update-judge/(?P<pk>\d+)$', JudgeViews.updatejudges, name='update-judges'),
    url(r'judge/delete-judge/(?P<pk>\d+)$', JudgeViews.delete_judge, name='delete-judge'),

    # Federation
    url(r'federation/add-registration/$', FederationViews.addFederationGroup, name='add-registration'),
    url(r'federation/add-federation/$', FederationViews.return_add_federation, name='add-federation'),
    url(r'federation/update-federation/(?P<pk>\d+)$', FederationViews.update_federation, name='update-federations'),
    url(r'federation/federations/$', FederationViews.return_federations, name='federations'),
    url(r'federation/delete-federation/(?P<pk>\d+)$', FederationViews.delete_federation, name='delete-federation'),

    url(r'federation/registration-list/$', FederationViews.registration_list, name='registration-list'),

    url(r'musabaka/taoluekle/$', AthleteViews.return_taolu, name='taolu-katagori'),
    url(r'musabaka/taolu/sil/(?P<pk>\d+)$', AthleteViews.categoryTaoluDelete, name='taolu-katagori-sil'),
    url(r'musabaka/taolu/Duzenle/(?P<pk>\d+)$', AthleteViews.categoryTaoluUpdate, name='taolu-katagori-duzenle'),

    # Taoulu yaş eklendisi
    url(r'musabaka/taoluekleyas/$', AthleteViews.return_taolu_years, name='yas-taolu-katagori'),
    url(r'musabaka/taoluekleyas/sil/(?P<pk>\d+)$', AthleteViews.categoryTaoluyearsDelete,
        name='yas-taolu-katagori-sil'),
    url(r'musabaka/taoluekleyas/Duzenle/(?P<pk>\d+)$', AthleteViews.categoryTaoluyearsUpdate,
        name='yas-taolu-katagori-duzenle'),

    # Sanda Yaş
    url(r'sporcu/sanda-ekleyas/$', AthleteViews.return_sanda_years, name='return_sanda_years'),
    url(r'sporcu/sanda-ekleyas/sil/(?P<pk>\d+)$', AthleteViews.categorySandayearsDelete, name='yas-sanda-katagori-sil'),
    url(r'sporcu/sanda-ekleyas/Duzenle/(?P<pk>\d+)$', AthleteViews.categorySandayearsUpdate,
        name='yas-sanda-katagori-duzenle'),

    url(r'competition/sanda-weight-category/$', CompetitionViews.return_sanda_weight_category,
        name='sanda-weight-category'),
    url(r'competition/sanda-weight-category-delete/(?P<pk>\d+)$', CompetitionViews.sanda_weight_category_delete,
        name='sanda-weight-category-delete'),
    url(r'competition/sanda-weight-category-update/(?P<pk>\d+)$', CompetitionViews.sanda_weight_category_update,
        name='sanda-weight-category-update'),
    url(r'competition/get_sanda-weight-category', CompetitionViews.get_weight_category, name='get_weight_category'),
    # url(r'showproducts', PdfConvertViews.show_products, name='showproducts'),
    # url(r'create-pdf', PdfConvertViews.pdf_report_create, name='create-pdf'),
    # url(r'java-test', PdfConvertViews.java, name='java-test'),
    url(r'profile/image/$', UsersViews.profile_image, name='profile_image'),

]

wushu/models.py
from django.db import models

# Create your models here.

wushu/models/Athlete.py
from django.contrib.auth.models import User
from django.db import models

from wushu.models.Federation import Federation
from wushu.models.Person import Person
from wushu.models.Communication import Communication


class Athlete(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    federation = models.ForeignKey(Federation, on_delete=models.CASCADE)
    ekg = models.FileField(upload_to='files/', null=True, blank=True, verbose_name='EKG')
    eeg = models.FileField(upload_to='files/', null=True, blank=True, verbose_name='EEG')

    def __str__(self):
        return '%s %s' % (self.person.name, self.person.surName)

    class Meta:
        ordering = ['pk']

wushu/models/CategoryItem.py
from django.db import models

from wushu.models.EnumFields import EnumFields


class CategoryItem(models.Model):
    name = models.CharField(blank=False, null=False, max_length=255)
    forWhichClazz = models.CharField(blank=False, null=False, max_length=255)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    branch = models.CharField(max_length=128, choices=EnumFields.BRANCH.value, null=True, blank=True,
                              verbose_name='Seçiniz')
    isFirst = models.BooleanField()

    def __str__(self):
        if self.branch == None:
            return '%s' % (self.name)
        else:
            return '%s' % (self.name + '-' + self.branch)

    class Meta:
        default_permissions = ()

wushu/models/City.py
from django.db import models


class City(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Şehir')

    def __str__(self):
        return '%s' % self.name

    def save(self, force_insert=False, force_update=False):
        self.name = self.name.upper()
        super(City, self).save(force_insert, force_update)

    class Meta:
        default_permissions = ()

wushu/models/Coach.py
from django.contrib.auth.models import User
from django.db import models

from wushu.models import Federation
from wushu.models.Person import Person


class Coach(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    federation = models.ForeignKey(Federation, on_delete=models.CASCADE)



    def __str__(self):
        return '%s %s' % (self.person.name, self.person.surName)

    class Meta:
        ordering = ['pk']
        default_permissions = ()

wushu/models/Communication.py
from django.db import models

from wushu.models.City import City
from wushu.models.Country import Country


class Communication(models.Model):

    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='İl')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='COUNTRY')

    class Meta:
        default_permissions = ()

wushu/models/Competition.py
from django.db import models

from wushu.models.EnumFields import EnumFields
from wushu.models.CompetitionCategori import CompetitionCategori


class Competition(models.Model):
    OPEN = 'Pre-Registration Open'
    CLOSED = 'Pre-Registration Completed'
    WAITED = 'On Standby'

    STATUS_CHOICES = (
        (OPEN, 'Pre-Registration Open'),
        (CLOSED, 'Pre-Registration Completed'),
        (WAITED, 'On Standby')
    )

    INTERNATIONAL = 'International'
    INTERSCHOOL = 'Interschool'
    INTERUNIVERSITY = 'Inter-University'
    NATIONAL = 'National'

    COMPETITION_TYPE = (
        (INTERNATIONAL, 'International'),
        (INTERSCHOOL, 'Interschool'),
        (INTERUNIVERSITY, 'Inter-University'),
        (NATIONAL, 'National')
    )

    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    startDate = models.DateTimeField()

    finishDate = models.DateTimeField()
    location = models.CharField(blank=False, null=False, max_length=1000)
    branch = models.CharField(max_length=128, verbose_name='Branş', choices=EnumFields.BRANCH.value)
    subBranch = models.CharField(max_length=128, verbose_name='Alt Branş', choices=EnumFields.SUBBRANCH.value)
    status = models.CharField(max_length=128, verbose_name='Kayıt Durumu', choices=STATUS_CHOICES, default=WAITED)
    type = models.CharField(max_length=128, verbose_name='Türü', choices=COMPETITION_TYPE, default=NATIONAL)
    registerStartDate = models.DateTimeField(db_column='registerStartDate', blank=True,
                                             null=True)  # Field name made lowercase.
    registerFinishDate = models.DateTimeField(db_column='registerFinishDate', blank=True,
                                              null=True)  # Field name made lowercase.

    # catergori ekleme

    categori = models.ManyToManyField(CompetitionCategori)

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        default_permissions = ()

wushu/models/CompetitionCategori.py
from django.db import models

from wushu.models.Athlete import Athlete
from wushu.models.TaoluCategory import TaoluCategory


# from wushu.models.CategoryItem import CategoryItem


class CompetitionCategori(models.Model):
    categori = models.ForeignKey(TaoluCategory, on_delete=models.CASCADE, verbose_name='Categori')
    athlete = models.ManyToManyField(Athlete)

    def __str__(self):
        return '%s' % (self.categori.categoryName)

    # yearcategori = models.ForeignKey(CategoryItem, on_delete=models.CASCADE, verbose_name='YearCategori')
    # class Meta:
    #     default_permissions = ()

wushu/models/Country.py
from django.db import models


class Country(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Ülke')

    def __str__(self):
        return '%s ' % self.name

    def save(self, force_insert=False, force_update=False):
        self.name = self.name.upper()
        super(Country, self).save(force_insert, force_update)

    class Meta:
        default_permissions = ()

wushu/models/EnumFields.py
import enum


class EnumFields(enum.Enum):
    class LEVELTYPE2(enum.Enum):
        VISA = 1
        GRADE = 2
        BELT = 3

    class LEVELTYPECOACH(enum.Enum):
        VISA = 1
        GRADE = 2

    class BRANCH2(enum.Enum):
        TAOLU = 1
        SANDA = 2
        WUSHU = 3

    class COMPSTATUS(enum.Enum):
        PREREGISTRATIONOPEN = 1
        PREREGISTRATIONCLOSED = 2
        COMPLETED = 3

    class COMPTYPE(enum.Enum):
        NATIONAL = 1
        INTERNATIONAL = 2

    WUSHU = 'WUSHU'
    AIKIDO = 'AIKIDO'
    WINGCHUN = 'WING CHUN'
    BUDAKADIO = 'BUDAKADIO'
    JEETKUNEDO = 'JEET KUNE DO KULELKAVIDO'

    BRANCH = (
        (AIKIDO, 'AIKIDO'),
        (WINGCHUN, 'WING CHUN'),
        (WUSHU, 'WUSHU'),
        (BUDAKADIO, 'BUDAKADIO'),
        (JEETKUNEDO, 'JEET KUNE DO KULELKAVIDO'),
    )

    SANDA = 'SANDA'
    TAOLU = 'TAOLU'
    TUISHOU = 'TUISHOU'

    SUBBRANCH = (
        (SANDA, 'SANDA'),
        (TAOLU, 'TAOLU'),

    )

    VISA = 'VISA'
    GRADE = 'GRADE'
    BELT = 'BELT'

    LEVELTYPE = (
        (VISA, 'VISA'),
        (GRADE, 'GRADE'),
        (BELT, 'BELT'),

    )

wushu/models/Federation.py
from django.contrib.auth.models import User
from django.db import models

from wushu.models.Person import Person


class Federation(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % self.person.country.name

    class Meta:
        ordering = ['pk']
        default_permissions = ()

wushu/models/Hotel.py
from django.db import models

from wushu.models import Federation
from wushu.models.Person import Person


class Hotel(models.Model):
    SINGLEROOM = 0
    DOUBLEROOM = 1

    HOTELTYPE = (
        (SINGLEROOM, 'SINGLE ROOM-81€'),
        (DOUBLEROOM, 'DOUBLE ROOM-63€'),

    )
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    registerStartDate = models.DateTimeField()
    registerFinishDate = models.DateTimeField()
    name = models.CharField(max_length=128, verbose_name='Hotel Room-Price', choices=HOTELTYPE)
    federation = models.ForeignKey(Federation, on_delete=models.CASCADE)
    totalDay = models.CharField(max_length=10, blank=True, null=True, verbose_name='Total Day')
    price = models.CharField(max_length=10, blank=True, null=True, verbose_name='Price')

    def __str__(self):
        return '%s %s' % (self.person.name, self.person.surName)

    class Meta:
        default_permissions = ()

wushu/models/Judge.py
from django.db import models

from wushu.models import Federation
from wushu.models.Person import Person
from wushu.models.Communication import Communication
from django.contrib.auth.models import User


class Judge(models.Model):
    ADAYHAKEM = 0
    HAKEM = 1


    COMPEVENTTYPE = (
        (ADAYHAKEM, 'CANDIDATE JUDGE'),
        (HAKEM, 'JUDGE'),

    )
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    category = models.IntegerField(null=True, blank=True, choices=COMPEVENTTYPE)
    federation = models.ForeignKey(Federation, on_delete=models.CASCADE)
    weight=models.IntegerField(null=True,blank=True,verbose_name='Kilo')
    height=models.IntegerField(null=True,blank=True,verbose_name='Boy')
    is_national=models.BooleanField(null=True,blank=True,verbose_name='Ulusal Hakem mi?')
    shirtSize=models.CharField(max_length=250,null=True,blank=True,verbose_name='Üst Beden')
    pantSize=models.CharField(max_length=250,null=True,blank=True,verbose_name='Alt Beden')





    def __str__(self):
        return '%s %s' % (self.person.name, self.person.surName)

    class Meta:
        default_permissions = ()

wushu/models/Logs.py
from django.contrib.auth.models import User
from django.db import models


class Logs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Üye Rolü', db_column='user')
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    subject = models.CharField(max_length=150, null=True)
    ip = models.CharField(max_length=20, null=True)

    def __str__(self):
        return '%s ' % self.user.get_full_name()

    class Meta:
        default_permissions = ()

wushu/templates/kategori/SandaWeightCategoryUpdate.html
{% extends 'base_layout.html' %}
{% block content %}




    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}


    <section class="content">

        <!-- /.row -->
        <!-- Main row -->
        <div class="row">


            <section class="col-lg-12 ">


                <div class="box-body">


                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Weight Category Update</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form method="post" role="form">
                            <div class="box-body">
                                {% csrf_token %}


                                <div class="form-group">
                                    <label> {{ sanda_weight_form.categoryName.label }}</label>
                                    {{ sanda_weight_form.categoryName }}
                                </div>
                                <div class="form-group">
                                    <label> {{ sanda_weight_form.explanation.label }}</label>
                                    {{ sanda_weight_form.gender }}
                                </div>
                                <div class="form-group">
                                    <label> {{ sanda_weight_form.isDuilian.label }}</label>
                                    {{ sanda_weight_form.ageGroup }}
                                </div>


                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>


                    </div>
                    <!-- /.box -->


                </div>
            </section>


        </div>
        <!-- /.row (main row) -->

    </section>







{% endblock %}

wushu/templates/kategori/sandaYearsCategory.html
{% extends 'base_layout.html' %}

{% block content %}




    <!-- success modal -->
    <div class="modal modal-success modal-success-food fade in" id="modal-success" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">İşlem Başarılı</h4>
                </div>
                <div class="modal-body successModal">
                    ...
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-outline btn-ok">Tamam</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal modal-danger fade in deneme22" tabindex="-1" role="dialog" id="modal-danger"
         aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Uyarı</h4>
                </div>
                <div class="modal-body">
                    <p>Silmek istediginizden emin misiniz?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left btn-ok" id="btn-conf"
                            data-dismiss="modal">Evet
                    </button>
                    <button type="button" class="btn btn-outline" id="btn-close">Hayır</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>



    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}






    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg">


            <div class="modal-content" style="height:fit-content">

                <div class="modal-header" style="background-color:#3c8dbc ">

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body bodys">
                    ...
                </div>
            </div>
        </div>
    </div>




    <section class="content">

        <!-- /.row -->
        <!-- Main row -->
        <div class="row">


            <section class="col-lg-12 ">


                <div class="box-body">


                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Sanda Yaş Kategorileri</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form method="post" role="form">
                            <div class="box-body">
                                {% csrf_token %}


                                <div class="form-group">
                                    <label> {{ sandayears_form.categoryName.label }}</label>
                                    {{ sandayears_form.categoryYear }}
                                </div>



                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Kaydet</button>
                            </div>
                        </form>


                        <table id="kategori" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Kategori Adı</th>
                                <th>Güncelleme/Silme</th>
                            </tr>
                            </thead>

                            <tbody>


                            {% if categoryitemm.all %}
                                {% for category in categoryitemm %}
                                    <tr>
                                        <td>{{ forloop.counter }} </td>
                                        <td>{{ category.categoryYear }}</td>

                                        <td>
                                           <div class="btn-group">
                                                <a href="{% url "wushu:yas-sanda-katagori-duzenle" category.pk %}"
                                                   type="button" class="btn btn-warning"><i
                                                        class="fa fa-edit"></i>İncele
                                                </a>

                                                <a class="btn btn-danger"
                                                   data-toggle="modal" onclick=deleteCategoryItem({{ category.pk }})><i
                                                        class="fa fa-trash"></i>Sil</a>
                                            </div>
                                        </td>

                                    </tr>

                                {% endfor %}
                            {% endif %}


                            </tbody>
                        </table>


                    </div>
                    <!-- /.box -->


                </div>
            </section>


        </div>
        <!-- /.row (main row) -->

    </section>


    <script>
        $(function () {
            $('#kategori').DataTable({
                'paging': false,
                'lengthChange': false,
                'searching': false,
                'ordering': false,
                'info': false,
                'autoWidth': true
            })

        })
    </script>
    <script>
        function deleteCategoryItem(id) {

            console.log(id);
            var html = ''
            $("#modal-danger").on("shown.bs.modal", function (e) {
                $("#btn-conf").click(function () {
                    $.ajax({

                        url: "{% url "wushu:yas-sanda-katagori-sil" pk=212121223232323232 %}".replace(/212121223232323232/, id.toString()),
                        type: "POST",
                        data: {
                            'csrfmiddlewaretoken': "{{  csrf_token  }}",
                            isActive: 'False'
                        },
                        success: function (result) {

                            html = 'Kategori Başarıyla Silindi';
                            debugger;
                            $(".successModal").html(html);
                            $('#modal-success').on("shown.bs.modal", function (e) {
                                $(".btn-ok").click(function () {

                                    window.location.replace("{% url "wushu:return_sanda_years" %}");

                                });

                            }).modal('show');


                            console.log(result.status)
                        }
                    });
                });
            }).modal('show');
            $('#btn-close').click(function () {
                $('#modal-danger').modal('hide');
            });

        }
    </script>



{% endblock %}